const productData = [
    {
      id: 1,
      name: "Toyota RAV4",
      image:
        "https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/ExtraImages/20191011034159_toyota-rav4-phev-1.jpg&w=700&q=90&c=1",
      year : 2021,
      people: 4,
      fuelType: 'Hybrid',
      mileage: 6.1,
      driveType: 'Automatic',
      price: 440,
    },
    {
      id: 2,
      name: "Honda CR-V",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 28,
      driveType: "Automatic",
      price: 350,
    },
    {
      id: 3,
      name: "Mazda CX-5",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 29,
      driveType: "Automatic",
      price: 370,
    },
    {
      id: 4,
      name: "Subaru Forester",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 360,
    },
    {
      id: 5,
      name: "Hyundai Tucson",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 26,
      driveType: "Automatic",
      price: 340,
    },
    {
      id: 6,
      name: "Kia Sportage",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 330,
    },
    {
      id: 7,
      name: "Toyota RAV4 Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 450,
    },
    {
      id: 8,
      name: "Honda CR-V Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 430,
    },
    {
      id: 9,
      name: "Mazda CX-5 Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 420,
    },
    {
      id: 10,
      name: "Subaru Forester Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 410,
    },
    {
      id: 11,
      name: "Toyota RAV4",
      image:
        "https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/ExtraImages/20191011034159_toyota-rav4-phev-1.jpg&w=700&q=90&c=1",
      year : 2021,
      people: 4,
      fuelType: 'Hybrid',
      mileage: 6.1,
      driveType: 'Automatic',
      price: 440,
    },
    {
      id: 12,
      name: "Honda CR-V",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 28,
      driveType: "Automatic",
      price: 350,
    },
    {
      id: 13,
      name: "Mazda CX-5",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 29,
      driveType: "Automatic",
      price: 370,
    },
    {
      id: 14,
      name: "Subaru Forester",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 360,
    },
    {
      id: 15,
      name: "Hyundai Tucson",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 26,
      driveType: "Automatic",
      price: 340,
    },
    {
      id: 16,
      name: "Kia Sportage",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 330,
    },
    {
      id: 17,
      name: "Toyota RAV4 Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 450,
    },
    {
      id: 18,
      name: "Honda CR-V Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 430,
    },
    {
      id: 19,
      name: "Mazda CX-5 Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 420,
    },
    {
      id: 20,
      name: "Subaru Forester Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 410,
    },
    // total 60
    {
      id: 21,
      name: "Toyota RAV4",
      image:
        "https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/ExtraImages/20191011034159_toyota-rav4-phev-1.jpg&w=700&q=90&c=1",
      year : 2021,
      people: 4,
      fuelType: 'Hybrid',
      mileage: 6.1,
      driveType: 'Automatic',
      price: 440,
    },
    {
      id: 22,
      name: "Honda CR-V",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 28,
      driveType: "Automatic",
      price: 350,
    },
    {
      id: 23,
      name: "Mazda CX-5",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      people: 5,
      fuelType: "Gas",
      mileage: 29,
      driveType: "Automatic",
      price: 370,
    },
    {
      id: 24,
      name: "Subaru Forester",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 360,
    },
    {
      id: 25,
      name: "Hyundai Tucson",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 26,
      driveType: "Automatic",
      price: 340,
    },
    {
      id: 26,
      name: "Kia Sportage",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 330,
    },
    {
      id: 27,
      name: "Toyota RAV4 Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 450,
    },
    {
      id: 28,
      name: "Honda CR-V Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 430,
    },
    {
      id: 29,
      name: "Mazda CX-5 Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 420,
    },
    {
      id: 30,
      name: "Subaru Forester Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 410,
    },
    // 10 more
    {
      id: 31,
      name: "Toyota RAV4",
      image:
        "https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/ExtraImages/20191011034159_toyota-rav4-phev-1.jpg&w=700&q=90&c=1",
      year : 2021,
      people: 4,
      fuelType: 'Hybrid',
      mileage: 6.1,
      driveType: 'Automatic',
      price: 440,
    },
    {
      id: 32,
      name: "Honda CR-V",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      people: 5,
      fuelType: "Gas",
      mileage: 28,
      driveType: "Automatic",
      price: 350,
    },
    {
      id: 33,
      name: "Mazda CX-5",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 29,
      driveType: "Automatic",
      price: 370,
    },
    {
      id: 34,
      name: "Subaru Forester",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 360,
    },
    {
      id: 35,
      name: "Hyundai Tucson",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 26,
      driveType: "Automatic",
      price: 340,
    },
    {
      id: 36,
      name: "Kia Sportage",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 330,
    },
    {
      id: 37,
      name: "Toyota RAV4 Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 450,
    },
    {
      id: 38,
      name: "Honda CR-V Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 430,
    },
    {
      id: 39,
      name: "Mazda CX-5 Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 420,
    },
    {
      id: 40,
      name: "Subaru Forester Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 410,
    },
    // 10 more
    {
      id: 41,
      name: "Toyota RAV4",
      image:
        "https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/ExtraImages/20191011034159_toyota-rav4-phev-1.jpg&w=700&q=90&c=1",
      year : 2021,
      people: 4,
      fuelType: 'Hybrid',
      mileage: 6.1,
      driveType: 'Automatic',
      price: 440,
    },
    {
      id: 42,
      name: "Honda CR-V",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      people: 5,
      fuelType: "Gas",
      mileage: 28,
      driveType: "Automatic",
      price: 350,
    },
    {
      id: 43,
      name: "Mazda CX-5",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 29,
      driveType: "Automatic",
      price: 370,
    },
    {
      id: 44,
      name: "Subaru Forester",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 360,
    },
    {
      id: 45,
      name: "Hyundai Tucson",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,

      fuelType: "Gas",
      mileage: 26,
      driveType: "Automatic",
      price: 340,
    },
    {
      id: 46,
      name: "Kia Sportage",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?  q=80",
      year: 2023,
      people: 5,
      fuelType: "Gas",
      mileage: 27,
      driveType: "Automatic",
      price: 330,
    },
    {
      id: 47,
      name: "Toyota RAV4 Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 450,
    },
    {
      id: 48, 
      name: "Honda CR-V Hybrid",
      image: "https://imgd-ct.aeplcdn.com/1280x720/cw/cars/discontinued/honda/cr-v-2007-2009.jpg?q=80",
      year: 2023,
      people: 5,
      fuelType: "Hybrid",
      mileage: 40,
      driveType: "Automatic",
      price: 430,
    },

    
  ];
  export default productData;